# Generated by Django 3.0.4 on 2020-04-03 08:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.IntegerField(blank=True)),
                ('submit_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.IntegerField(blank=True)),
                ('submit_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='symptom.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('shortness_of_breath', models.BooleanField(default=False)),
                ('cough', models.BooleanField(default=False)),
                ('high_fever', models.BooleanField(default=False)),
                ('tiredness', models.BooleanField(default=False)),
                ('sore_throat', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('submit_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='symptom.Zone')),
            ],
        ),
    ]
