# Generated by Django 3.0.4 on 2020-04-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='user_id',
        ),
    ]
