# Generated by Django 3.0.4 on 2020-04-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0002_auto_20200403_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='cough',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='high_fever',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='shortness_of_breath',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='sore_throat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='tiredness',
            field=models.IntegerField(default=0),
        ),
    ]
