# Generated by Django 2.0.1 on 2020-04-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0004_symptom_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shortness_of_breath', models.IntegerField(default=0)),
                ('cough', models.IntegerField(default=0)),
                ('high_fever', models.IntegerField(default=0)),
                ('tiredness', models.IntegerField(default=0)),
                ('sore_throat', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
