# Generated by Django 2.0.1 on 2020-04-15 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0005_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='submit_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
